Add i18n and language selector
GeorgesMainville/YoBig pull request #15
Opened 2021-05-29 22:29 UTC by GeorgesMainville

## Yo what's up big??

[Je veux avoir un site web traduisible (I18N)](https://yobig.atlassian.net/browse/WEB-8)

## 💡 A bit of brainstorming

<**EDIT ME**: If you made architectural decisions or want to talk about something, discuss it here.>

## 🖼 Gallery

<**Screenshots time!**>

## 😎 How did you get Chad's approval?

- [ ] Unit and integration tests
- [ ] Configurations
- [ ] Permissions
- [ ] Preliminary self review
- [ ] Updated the documentation

2021-06-28 17:19 UTC, EtienneSimoneau requested changes

2021-06-28 17:19 UTC, EtienneSimoneau commented on WebApp/src/components/LangSelector/LangSelectorLogic.tsx
> +type LangSelectorLogicProps = {
Nitpick: J'aime vraiment pas les abréviations. Je trouve que ça réduit la lisibilité du code. C'est vraiment un nitpick car ici c'est évident que lang veut dire language, mais en lisant le code, j'aime beaucoup mieux lire "LanguageSelectorLogicProps" que "LangSelectorLogicProps"

 Je dirais que c'est surtout à ce niveau que ça m'énerve beaucoup: 
 const { setLang, lang } = langContext;
 
 J'aimerais mieux voir:
 const { language, setLanguage } = languageContext;

Dis-moi ce que tu en penses.

2021-06-28 17:19 UTC, EtienneSimoneau commented on WebApp/src/components/LangSelector/LangSelectorLogic.tsx
> +type LangSelectorLogicProps = {
fun fact: on dirait que je lis "langue" en français donc ça m'trigger

2021-06-28 17:19 UTC, EtienneSimoneau commented on WebApp/src/components/BasicTest/BasicTestContainer.tsx
> +        <FormattedMessage id={quote} />
J'aime tellement pas le terme "FormattedMessage", on dirait tellement pas que c'est quelque chose qui fait un automatic translate selon la culture, mais j'pense pas qu'on a contrôle la dessus juste mon POV

2021-06-29 15:23 UTC, GeorgesMainville commented on WebApp/src/components/BasicTest/BasicTestContainer.tsx
> +        <FormattedMessage id={quote} />
Dans le cas ou FormattedMessage ne permeterrait que de translate une string je suis d'accord mais l'outil est plus puissant que ça. https://formatjs.io/docs/react-intl/components/#formattedmessage

2021-06-29 15:36 UTC, GeorgesMainville commented on WebApp/src/components/BasicTest/BasicTestContainer.style.tsx
> +export const Container = styled.div`
Pourquoi le rename ici?
- J'ai changer ExploreContainer pour BasicTestContainer parce que le nom du fichier est BasicTestContainer. Ça créé un conflict entre BasicTestContainer le component et BasicTestContainer le styling. J'ai alors changer BasicTestContainer pour Container a la place de BasicTestContainerContainer.

2021-06-29 15:38 UTC, GeorgesMainville commented on WebApp/src/components/BasicTest/BasicTestContainer.style.tsx
> +export const Container = styled.div`
Le naming dans ce fichier là est pas perfect mais le component va disparaitre.

2021-06-29 15:39 UTC, GeorgesMainville commented on WebApp/src/components/BasicTest/BasicTestContainer.style.tsx
> +export const Container = styled.div`
Mais ouin généralement je préfère 'ComponentNameContainer'.

2021-06-29 15:51 UTC, GeorgesMainville commented on WebApp/src/lang/en.json
> +  "explore_container_change_quote": "Change quote"
Je crois que je préfère.
```
"change_quote": "Change quote"
"quotes": {
  "etien": "Etien est le meilleur programmeur",
  "georges": "Georges est le meilleur programmeur",
}
```

2021-06-29 15:52 UTC, GeorgesMainville commented on WebApp/src/lang/en.json
> +  "explore_container_change_quote": "Change quote"
Mais si on peu en reparler mercredi ça serait interessant.

2021-06-29 15:55 UTC, EtienneSimoneau commented on WebApp/src/components/BasicTest/BasicTestContainer.style.tsx
> +export const Container = styled.div`
Oh ok j'ai mal interprété, c'est parce qu'on est dans le fichier BasicTestContainer.style.tsx, je croyais que tu changeais le naming du composant à cause du style et la j'etais vraiment pas d'accord mais l'inverse est correcte.

Comme on peut assumer je crois que chaque composant va avoir un style pour son container, peut-être que pour le styling on pourrait appeler ça "ComponentContainer". "Container n'est pas si mal non plus.

Donc on aurait le component qui respecterait le naming de son style et le style qui définit dans l'fond un styled component qui représente le wrapper du component au complet d'où "ComponentContainer" pi probablement que chaque component va avoir un styling pour son "ComponentContainer"

2021-06-29 16:01 UTC, EtienneSimoneau commented on WebApp/src/components/BasicTest/BasicTestContainer.tsx
> +        <FormattedMessage id={quote} />
Intéressant, je crois qu'il n'y a pas ça dans React Native!

2021-06-30 19:46 UTC, GeorgesMainville commented on WebApp/src/components/BasicTest/BasicTestContainer.style.tsx
> +export const Container = styled.div`
"Comme on peut assumer je crois que chaque composant va avoir un style pour son container, peut-être que pour le styling on pourrait appeler ça "ComponentContainer". "Container n'est pas si mal non plus."
Exacte, le seul problème que je peux voir c'est si on a de quoi du genre :
`
import Container from 'styles.js'
import Container from './styles/shared.js'
`
mais dans ce cas là on pourai faire
`
import Container as ComponentNameContainer from 'styles.js'
import Container from './styles/shared.js'
`

2021-06-30 19:53 UTC, GeorgesMainville commented on WebApp/src/components/LangSelector/LangSelectorLogic.tsx
> +type LangSelectorLogicProps = {
Je suis d'accord d'enlever les abréviations le plus possible.

2021-06-30 22:55 UTC, EtienneSimoneau commented on WebApp/src/components/BasicTest/BasicTestContainer.style.tsx
> +export const Container = styled.div`
Sounds good to me!

2021-07-01 02:40 UTC, EtienneSimoneau requested changes

2021-07-01 02:40 UTC, EtienneSimoneau commented on WebApp/src/utils/tests-utils.tsx
> +  const tranlations: any = i18n.get(DEFAULT_LANGUAGE);
nitpick: 
```suggestion
  const translations: any = i18n.get(DEFAULT_LANGUAGE);
```

2021-07-01 02:41 UTC, EtienneSimoneau approved these changes
LGTM

2021-07-01 02:42 UTC, merged